=== jcoombs3/bbus-inter-widget-comm/sdlc/content/$schema/assets/SC_Unit_Article.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"title": "Article",
	"description": "An article with a title, introduction and sub headings.",
	"type": "object",
  "properties": {
		"title": {
			"title": "Title",
			"type": "string",
			"description": "Title of the article.",
			"metadata": {
				"placeholderText": "Enter a title",
				"order": 1
			}
		},
		"picture": {
			"title": "Picture",
			"type": "string",
			"description": "Picture accompanying the article. Optional.",
			"metadata": {
				"renderingHint": "image",
				"infoText": "Picture accompanying the article (optional)",
				"order": 2
			}
		},
		"introduction": {
			"title": "Introduction",
			"type": "string",
			"description": "A paragraph introducing the article.",
			"metadata": {
				"renderingHint": "multiline",
				"infoText": "A paragraph introducing the article",
				"order": 3
			}
		},
		"sections": {
			"title": "Sections",
			"type": "array",
			"minItems": 1,
			"description": "Sections forming the article. Each section has a sub heading.",
			"metadata": {
				"order": 4
			},
			"items": {
				"title": "Section",
				"type": "object",
				"description": "One section with a sub heading and paragraphs.",
				"properties": {
					"title": {
						"title": "Title",
						"type": "string",
						"description": "A sub heading of a section.",
						"metadata": {
							"placeholderText": "Enter a heading"
						}
					},
					"paragraphs": {
						"title": "Paragraphs",
						"type": "array",
						"minItems": 1,
						"description": "Paragraphs of a section.",
						"items": {
							"title": "Paragraph",
							"type": "string",
							"description": "A paragraph.",
							"metadata": {
								"renderingHint": "multiline",
								"infoText": "One paragraph"
							}
						}
					}
				},
				"required": [
					"title"
				]
			}
		}
	},
	"required": [
		"title",
		"introduction"
	]
}

=== jcoombs3/bbus-inter-widget-comm/sdlc/content/Foobar-Article.json
{
	"$schema": "./$schema/assets/SC_Unit_Article.json",
	"title": "An Article Title",
	"picture": "rel:placeholder.png",
	"introduction": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
	"sections": [
		{
			"title": "A Section Title",
			"paragraphs": [
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
				"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
			]
		}
	]
}
